# Generated by Django 4.1.7 on 2023-02-15 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0013_alter_comment_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_official_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
