# Generated by Django 4.1.7 on 2023-02-15 23:32

import answers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0013_alter_comment_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_official_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='expertvotes',
            field=models.ManyToManyField(related_name='expertvote_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolutionExcerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('edittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('long_id', models.CharField(default=answers.models.generate_long_id, max_length=256, unique=True)),
                ('from_page_num', models.IntegerField()),
                ('from_rel_height', models.FloatField()),
                ('from_rel_width', models.FloatField(default=0.0)),
                ('to_page_num', models.IntegerField()),
                ('to_rel_height', models.FloatField()),
                ('to_rel_width', models.FloatField(default=0.0)),
                ('answer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answersection')),
                ('downvotes', models.ManyToManyField(related_name='downvoted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('expertvotes', models.ManyToManyField(related_name='expertvote_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(related_name='upvoted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
