[tools]
node = "24.20.0"
prek = "0.5.2"
uv = "0.12.9"
yarn = "4.18.0"

[env]
_.file = "backend/.env.development"
# overwrite relevant env.development envs for non-docker-compose execution
SIP_POSTGRES_DB_SERVER = "localhost"
SIP_S3_FILES_HOST = "localhost"

IS_DEBUG = "true"
COMSOL_ASSETS_FOLDER = "../frontend/public/"
