/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorSchema,
  FeedbackApiFlagsBody,
  FeedbackApiRepliesBody,
  FeedbackApiSubmitBody,
  FeedbackList,
  ImageList,
  ImageRemoveResponse,
  ImageUploadResponse,
  ImagesApiUploadImageBody,
} from "../../model";

/**
 * @summary Submit
 */
export type feedbackApiSubmitResponse200 = {
  data: void;
  status: 200;
};

export type feedbackApiSubmitResponseSuccess = feedbackApiSubmitResponse200 & {
  headers: Headers;
};
export type feedbackApiSubmitResponse = feedbackApiSubmitResponseSuccess;

export const getFeedbackApiSubmitUrl = () => {
  return `/api/feedback/submit/`;
};

export const feedbackApiSubmit = async (
  feedbackApiSubmitBody: FeedbackApiSubmitBody,
  options?: RequestInit,
): Promise<feedbackApiSubmitResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`text`, feedbackApiSubmitBody.text);

  const res = await fetch(getFeedbackApiSubmitUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: feedbackApiSubmitResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as feedbackApiSubmitResponse;
};

export const getFeedbackApiSubmitMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof feedbackApiSubmit>>,
    TError,
    { data: FeedbackApiSubmitBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof feedbackApiSubmit>>,
  TError,
  { data: FeedbackApiSubmitBody },
  TContext
> => {
  const mutationKey = ["feedbackApiSubmit"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof feedbackApiSubmit>>,
    { data: FeedbackApiSubmitBody }
  > = props => {
    const { data } = props ?? {};

    return feedbackApiSubmit(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FeedbackApiSubmitMutationResult = NonNullable<
  Awaited<ReturnType<typeof feedbackApiSubmit>>
>;
export type FeedbackApiSubmitMutationBody = FeedbackApiSubmitBody;
export type FeedbackApiSubmitMutationError = unknown;

/**
 * @summary Submit
 */
export const useFeedbackApiSubmit = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof feedbackApiSubmit>>,
      TError,
      { data: FeedbackApiSubmitBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof feedbackApiSubmit>>,
  TError,
  { data: FeedbackApiSubmitBody },
  TContext
> => {
  return useMutation(getFeedbackApiSubmitMutationOptions(options), queryClient);
};
/**
 * @summary List All
 */
export type feedbackApiListAllResponse200 = {
  data: FeedbackList;
  status: 200;
};

export type feedbackApiListAllResponseSuccess =
  feedbackApiListAllResponse200 & {
    headers: Headers;
  };
export type feedbackApiListAllResponse = feedbackApiListAllResponseSuccess;

export const getFeedbackApiListAllUrl = () => {
  return `/api/feedback/list/`;
};

export const feedbackApiListAll = async (
  options?: RequestInit,
): Promise<feedbackApiListAllResponse> => {
  const res = await fetch(getFeedbackApiListAllUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: feedbackApiListAllResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as feedbackApiListAllResponse;
};

export const getFeedbackApiListAllQueryKey = () => {
  return [`/api/feedback/list/`] as const;
};

export const getFeedbackApiListAllQueryOptions = <
  TData = Awaited<ReturnType<typeof feedbackApiListAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof feedbackApiListAll>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFeedbackApiListAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof feedbackApiListAll>>
  > = ({ signal }) => feedbackApiListAll({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof feedbackApiListAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FeedbackApiListAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof feedbackApiListAll>>
>;
export type FeedbackApiListAllQueryError = unknown;

export function useFeedbackApiListAll<
  TData = Awaited<ReturnType<typeof feedbackApiListAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof feedbackApiListAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackApiListAll>>,
          TError,
          Awaited<ReturnType<typeof feedbackApiListAll>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFeedbackApiListAll<
  TData = Awaited<ReturnType<typeof feedbackApiListAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof feedbackApiListAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof feedbackApiListAll>>,
          TError,
          Awaited<ReturnType<typeof feedbackApiListAll>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFeedbackApiListAll<
  TData = Awaited<ReturnType<typeof feedbackApiListAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof feedbackApiListAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List All
 */

export function useFeedbackApiListAll<
  TData = Awaited<ReturnType<typeof feedbackApiListAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof feedbackApiListAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFeedbackApiListAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Replies
 */
export type feedbackApiRepliesResponse200 = {
  data: void;
  status: 200;
};

export type feedbackApiRepliesResponseSuccess =
  feedbackApiRepliesResponse200 & {
    headers: Headers;
  };
export type feedbackApiRepliesResponse = feedbackApiRepliesResponseSuccess;

export const getFeedbackApiRepliesUrl = (feedbackid: number) => {
  return `/api/feedback/reply/${feedbackid}/`;
};

export const feedbackApiReplies = async (
  feedbackid: number,
  feedbackApiRepliesBody: FeedbackApiRepliesBody,
  options?: RequestInit,
): Promise<feedbackApiRepliesResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`reply`, feedbackApiRepliesBody.reply);

  const res = await fetch(getFeedbackApiRepliesUrl(feedbackid), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: feedbackApiRepliesResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as feedbackApiRepliesResponse;
};

export const getFeedbackApiRepliesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof feedbackApiReplies>>,
    TError,
    { feedbackid: number; data: FeedbackApiRepliesBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof feedbackApiReplies>>,
  TError,
  { feedbackid: number; data: FeedbackApiRepliesBody },
  TContext
> => {
  const mutationKey = ["feedbackApiReplies"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof feedbackApiReplies>>,
    { feedbackid: number; data: FeedbackApiRepliesBody }
  > = props => {
    const { feedbackid, data } = props ?? {};

    return feedbackApiReplies(feedbackid, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FeedbackApiRepliesMutationResult = NonNullable<
  Awaited<ReturnType<typeof feedbackApiReplies>>
>;
export type FeedbackApiRepliesMutationBody = FeedbackApiRepliesBody;
export type FeedbackApiRepliesMutationError = unknown;

/**
 * @summary Replies
 */
export const useFeedbackApiReplies = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof feedbackApiReplies>>,
      TError,
      { feedbackid: number; data: FeedbackApiRepliesBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof feedbackApiReplies>>,
  TError,
  { feedbackid: number; data: FeedbackApiRepliesBody },
  TContext
> => {
  return useMutation(
    getFeedbackApiRepliesMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Flags
 */
export type feedbackApiFlagsResponse200 = {
  data: void;
  status: 200;
};

export type feedbackApiFlagsResponseSuccess = feedbackApiFlagsResponse200 & {
  headers: Headers;
};
export type feedbackApiFlagsResponse = feedbackApiFlagsResponseSuccess;

export const getFeedbackApiFlagsUrl = (feedbackid: number) => {
  return `/api/feedback/flags/${feedbackid}/`;
};

export const feedbackApiFlags = async (
  feedbackid: number,
  feedbackApiFlagsBody: FeedbackApiFlagsBody,
  options?: RequestInit,
): Promise<feedbackApiFlagsResponse> => {
  const formUrlEncoded = new URLSearchParams();
  if (
    feedbackApiFlagsBody.read !== undefined &&
    feedbackApiFlagsBody.read !== null
  ) {
    formUrlEncoded.append(`read`, feedbackApiFlagsBody.read.toString());
  }
  if (
    feedbackApiFlagsBody.done !== undefined &&
    feedbackApiFlagsBody.done !== null
  ) {
    formUrlEncoded.append(`done`, feedbackApiFlagsBody.done.toString());
  }

  const res = await fetch(getFeedbackApiFlagsUrl(feedbackid), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: feedbackApiFlagsResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as feedbackApiFlagsResponse;
};

export const getFeedbackApiFlagsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof feedbackApiFlags>>,
    TError,
    { feedbackid: number; data: FeedbackApiFlagsBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof feedbackApiFlags>>,
  TError,
  { feedbackid: number; data: FeedbackApiFlagsBody },
  TContext
> => {
  const mutationKey = ["feedbackApiFlags"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof feedbackApiFlags>>,
    { feedbackid: number; data: FeedbackApiFlagsBody }
  > = props => {
    const { feedbackid, data } = props ?? {};

    return feedbackApiFlags(feedbackid, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FeedbackApiFlagsMutationResult = NonNullable<
  Awaited<ReturnType<typeof feedbackApiFlags>>
>;
export type FeedbackApiFlagsMutationBody = FeedbackApiFlagsBody;
export type FeedbackApiFlagsMutationError = unknown;

/**
 * @summary Flags
 */
export const useFeedbackApiFlags = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof feedbackApiFlags>>,
      TError,
      { feedbackid: number; data: FeedbackApiFlagsBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof feedbackApiFlags>>,
  TError,
  { feedbackid: number; data: FeedbackApiFlagsBody },
  TContext
> => {
  return useMutation(getFeedbackApiFlagsMutationOptions(options), queryClient);
};
/**
 * @summary List Images
 */
export type imagesApiListImagesResponse200 = {
  data: ImageList;
  status: 200;
};

export type imagesApiListImagesResponseSuccess =
  imagesApiListImagesResponse200 & {
    headers: Headers;
  };
export type imagesApiListImagesResponse = imagesApiListImagesResponseSuccess;

export const getImagesApiListImagesUrl = () => {
  return `/api/image/list/`;
};

export const imagesApiListImages = async (
  options?: RequestInit,
): Promise<imagesApiListImagesResponse> => {
  const res = await fetch(getImagesApiListImagesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: imagesApiListImagesResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as imagesApiListImagesResponse;
};

export const getImagesApiListImagesQueryKey = () => {
  return [`/api/image/list/`] as const;
};

export const getImagesApiListImagesQueryOptions = <
  TData = Awaited<ReturnType<typeof imagesApiListImages>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof imagesApiListImages>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getImagesApiListImagesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof imagesApiListImages>>
  > = ({ signal }) => imagesApiListImages({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof imagesApiListImages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ImagesApiListImagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof imagesApiListImages>>
>;
export type ImagesApiListImagesQueryError = unknown;

export function useImagesApiListImages<
  TData = Awaited<ReturnType<typeof imagesApiListImages>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiListImages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof imagesApiListImages>>,
          TError,
          Awaited<ReturnType<typeof imagesApiListImages>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useImagesApiListImages<
  TData = Awaited<ReturnType<typeof imagesApiListImages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiListImages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof imagesApiListImages>>,
          TError,
          Awaited<ReturnType<typeof imagesApiListImages>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useImagesApiListImages<
  TData = Awaited<ReturnType<typeof imagesApiListImages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiListImages>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Images
 */

export function useImagesApiListImages<
  TData = Awaited<ReturnType<typeof imagesApiListImages>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiListImages>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getImagesApiListImagesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Upload Image
 */
export type imagesApiUploadImageResponse200 = {
  data: ImageUploadResponse;
  status: 200;
};

export type imagesApiUploadImageResponse400 = {
  data: ErrorSchema;
  status: 400;
};

export type imagesApiUploadImageResponseSuccess =
  imagesApiUploadImageResponse200 & {
    headers: Headers;
  };
export type imagesApiUploadImageResponseError =
  imagesApiUploadImageResponse400 & {
    headers: Headers;
  };

export type imagesApiUploadImageResponse =
  | imagesApiUploadImageResponseSuccess
  | imagesApiUploadImageResponseError;

export const getImagesApiUploadImageUrl = () => {
  return `/api/image/upload/`;
};

export const imagesApiUploadImage = async (
  imagesApiUploadImageBody: ImagesApiUploadImageBody,
  options?: RequestInit,
): Promise<imagesApiUploadImageResponse> => {
  const formData = new FormData();
  formData.append(`file`, imagesApiUploadImageBody.file);

  const res = await fetch(getImagesApiUploadImageUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: imagesApiUploadImageResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as imagesApiUploadImageResponse;
};

export const getImagesApiUploadImageMutationOptions = <
  TError = ErrorSchema,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof imagesApiUploadImage>>,
    TError,
    { data: ImagesApiUploadImageBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof imagesApiUploadImage>>,
  TError,
  { data: ImagesApiUploadImageBody },
  TContext
> => {
  const mutationKey = ["imagesApiUploadImage"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof imagesApiUploadImage>>,
    { data: ImagesApiUploadImageBody }
  > = props => {
    const { data } = props ?? {};

    return imagesApiUploadImage(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ImagesApiUploadImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof imagesApiUploadImage>>
>;
export type ImagesApiUploadImageMutationBody = ImagesApiUploadImageBody;
export type ImagesApiUploadImageMutationError = ErrorSchema;

/**
 * @summary Upload Image
 */
export const useImagesApiUploadImage = <
  TError = ErrorSchema,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof imagesApiUploadImage>>,
      TError,
      { data: ImagesApiUploadImageBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof imagesApiUploadImage>>,
  TError,
  { data: ImagesApiUploadImageBody },
  TContext
> => {
  return useMutation(
    getImagesApiUploadImageMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Remove Image
 */
export type imagesApiRemoveImageResponse200 = {
  data: ImageRemoveResponse;
  status: 200;
};

export type imagesApiRemoveImageResponse403 = {
  data: ErrorSchema;
  status: 403;
};

export type imagesApiRemoveImageResponseSuccess =
  imagesApiRemoveImageResponse200 & {
    headers: Headers;
  };
export type imagesApiRemoveImageResponseError =
  imagesApiRemoveImageResponse403 & {
    headers: Headers;
  };

export type imagesApiRemoveImageResponse =
  | imagesApiRemoveImageResponseSuccess
  | imagesApiRemoveImageResponseError;

export const getImagesApiRemoveImageUrl = (filename: string) => {
  return `/api/image/remove/${filename}/`;
};

export const imagesApiRemoveImage = async (
  filename: string,
  options?: RequestInit,
): Promise<imagesApiRemoveImageResponse> => {
  const res = await fetch(getImagesApiRemoveImageUrl(filename), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: imagesApiRemoveImageResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as imagesApiRemoveImageResponse;
};

export const getImagesApiRemoveImageMutationOptions = <
  TError = ErrorSchema,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof imagesApiRemoveImage>>,
    TError,
    { filename: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof imagesApiRemoveImage>>,
  TError,
  { filename: string },
  TContext
> => {
  const mutationKey = ["imagesApiRemoveImage"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof imagesApiRemoveImage>>,
    { filename: string }
  > = props => {
    const { filename } = props ?? {};

    return imagesApiRemoveImage(filename, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ImagesApiRemoveImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof imagesApiRemoveImage>>
>;

export type ImagesApiRemoveImageMutationError = ErrorSchema;

/**
 * @summary Remove Image
 */
export const useImagesApiRemoveImage = <
  TError = ErrorSchema,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof imagesApiRemoveImage>>,
      TError,
      { filename: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof imagesApiRemoveImage>>,
  TError,
  { filename: string },
  TContext
> => {
  return useMutation(
    getImagesApiRemoveImageMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Get Image
 */
export type imagesApiGetImageResponse200 = {
  data: void;
  status: 200;
};

export type imagesApiGetImageResponseSuccess = imagesApiGetImageResponse200 & {
  headers: Headers;
};
export type imagesApiGetImageResponse = imagesApiGetImageResponseSuccess;

export const getImagesApiGetImageUrl = (filename: string) => {
  return `/api/image/get/${filename}/`;
};

export const imagesApiGetImage = async (
  filename: string,
  options?: RequestInit,
): Promise<imagesApiGetImageResponse> => {
  const res = await fetch(getImagesApiGetImageUrl(filename), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: imagesApiGetImageResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as imagesApiGetImageResponse;
};

export const getImagesApiGetImageQueryKey = (filename: string) => {
  return [`/api/image/get/${filename}/`] as const;
};

export const getImagesApiGetImageQueryOptions = <
  TData = Awaited<ReturnType<typeof imagesApiGetImage>>,
  TError = unknown,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiGetImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getImagesApiGetImageQueryKey(filename);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof imagesApiGetImage>>
  > = ({ signal }) => imagesApiGetImage(filename, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!filename,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof imagesApiGetImage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ImagesApiGetImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof imagesApiGetImage>>
>;
export type ImagesApiGetImageQueryError = unknown;

export function useImagesApiGetImage<
  TData = Awaited<ReturnType<typeof imagesApiGetImage>>,
  TError = unknown,
>(
  filename: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiGetImage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof imagesApiGetImage>>,
          TError,
          Awaited<ReturnType<typeof imagesApiGetImage>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useImagesApiGetImage<
  TData = Awaited<ReturnType<typeof imagesApiGetImage>>,
  TError = unknown,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiGetImage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof imagesApiGetImage>>,
          TError,
          Awaited<ReturnType<typeof imagesApiGetImage>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useImagesApiGetImage<
  TData = Awaited<ReturnType<typeof imagesApiGetImage>>,
  TError = unknown,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiGetImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Image
 */

export function useImagesApiGetImage<
  TData = Awaited<ReturnType<typeof imagesApiGetImage>>,
  TError = unknown,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof imagesApiGetImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getImagesApiGetImageQueryOptions(filename, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
