/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface FeedbackOut {
  oid: number;
  author: string;
  authorDisplayName: string;
  reply_time: string | null;
  text: string;
  time?: string;
  read?: boolean;
  done?: boolean;
  reply?: string | null;
}
