# Generated by Django 3.2 on 2021-04-30 16:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_auto_20210404_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='documents_c_search__02d77d_gin',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_c_search__fb153e_gin'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='documents.document'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
