# Generated by Django 5.2.13 on 2026-05-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_normalise_documentfile_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pending_transfer_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_document_transfer_receive_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
