# Generated by Django 5.2.17 on 2026-08-24 13:00

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0022_user_solved_exams"),
        ("categories", "0013_categoryuserpinned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "edited_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateField()),
                ("fulfilled_time", models.DateTimeField(blank=True, null=True)),
                ("checked_time", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_state",
                    models.TextField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("excused", "Excused"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
                (
                    "uploaded_transcript",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="answers.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("created_time__lte", models.F("edited_time"))
                        ),
                        name="mandate_created_before_edited",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "created_time__lte",
                                django.db.models.functions.comparison.Cast(
                                    models.F("due_date"),
                                    output_field=models.DateTimeField(),
                                ),
                            )
                        ),
                        name="mandate_created_before_due_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fulfilled_time__isnull", True),
                            ("created_time__lte", models.F("fulfilled_time")),
                            _connector="OR",
                        ),
                        name="mandate_created_before_fulfilled",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("checked_time__isnull", True),
                            models.Q(
                                ("fulfilled_time__isnull", False),
                                ("fulfilled_time__lte", models.F("checked_time")),
                            ),
                            _connector="OR",
                        ),
                        name="mandate_fulfilled_before_checked",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("checked_state__isnull", True),
                                ("checked_time__isnull", True),
                            ),
                            models.Q(
                                ("checked_state__isnull", False),
                                ("checked_time__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="mandate_check_state_only_if_checked",
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("mandate"),
                models.Model,
            ),
        ),
    ]
